Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
Traceback (most recent call last):
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/main.py", line 7, in <module>
    from lm_eval import tasks, evaluator
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/evaluator.py", line 6, in <module>
    import lm_eval.models
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/__init__.py", line 1, in <module>
    from . import gpt2
  File "/home/jc3464/QuantHerd/lm-evaluation-harness/lm_eval/models/gpt2.py", line 10, in <module>
    from quantize.fake_quant import load_OPTQ_local
  File "/home/jc3464/QuantHerd/quant-balance-herd-smooth/quantize/fake_quant.py", line 21, in <module>
    from safetensors import safe_open
ModuleNotFoundError: No module named 'safetensors'
